services:
  jwt-service:
    build:
      context: ./src
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1

  postgres:
    image: 'postgres:17'
    ports:
      - "5436:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jwtAuth
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
